[build-system]
requires = [
    "setuptools >= 43.0.0",
    "wheel >= 0.32.0",
]
build-backend = "setuptools.build_meta"

[tool.towncrier]
directory = "changes"
package = "rubicon.objc"
filename = "docs/background/releases.rst"
title_format = "{version} ({project_date})"
issue_format = "`#{issue} <https://github.com/beeware/rubicon-objc/issues/{issue}>`_"
template = "changes/template.rst"
underlines = ["-", "^", "\""]
